### ISSUE TITLE
#01 User Manager UI 수정

### ISSUE THREAD

**Issue by jinho9613** [jinho9613/work_logstack#1]
- [x] 정보에 입사일 추가하기(명훈)
- [x] List로 가는 버튼을 왼쪽 위로 옮기기(명훈)
- [x] 매니저 권한 주기, 퇴사 처리 버튼은 이름 옆으로 옮기기(명훈)
- [x] Team, Position 수정은 누르자 마자 반영 되도록(명훈)
- [x] 팀, position 수정을 한줄로 UI 변경(명훈)

**Comment by jinho9613** [comment]
어찌 저찌 했음

**Comment by yoon-myunghoon** [comment]
명훈 진행중

**Comment by yoon-myunghoon** [comment]
> 정보에 입사일 추가하기
- profile 모델에 start_date 필드 추가(마이그레이션 필요), ProfileForm, user_info.html, user_info_edit.html 수정
