### ISSUE TITLE
#04 퇴근 일지 작성후 시간 기록

### ISSUE THREAD

**Issue by jinho9613** [jinho9613/work_logstack#4]
퇴근일지 작성후  퇴근 시간 기록

**Comment by yoon-myunghoon** [comment]
윤명훈 진행중

**Comment by yoon-myunghoon** [comment]
- 일반적인 경우(매니저가 아닌 경우), 퇴근 버튼을 눌렀을 때 퇴근 일지 작성 페이지로 이동, 퇴근 일지를 작성한 후에 end time이 기록되면서 로그아웃으로 redirect해줌
- 이미 퇴근일지를 작성하고 로그아웃한 상태에서 재로그인한 경우, 퇴근 버튼을 누르면 퇴근 일지 작성페이지를 거치지 않고 바로 로그아웃처리됨(이때 퇴근 시간이 갱신됨)
- 업무 시작 버튼을 누르지 않은 경우(매니저인 경우), 퇴근 버튼을 누르면 퇴근 일지 작성페이지를 거치지 않고 바로 로그아웃 처리됨(퇴근 시간이 따로 기록되지 않음)
