### ISSUE TITLE
#05 Nav UI 수정

### ISSUE THREAD

**Issue by jinho9613** [jinho9613/work_logstack#5]
home 버튼 없애기(완료 - 명훈)

LOGSTACK 로고에 index 페이지로 갈 수 있도록 링크 달기(완료 - 명훈)

로그아웃 버튼을 퇴근 버튼으로 수정(완료 - 명훈)

로그아웃 하면 곧바로 로그인 화면으로 이동(완료 - 유진)

**Comment by yoon-myunghoon** [comment]
윤명훈 진행중
- 로그아웃 버튼을 퇴근 버튼으로 수정

**Comment by yoon-myunghoon** [comment]
진행중
- home 버튼 없애기
- LOGSTACK 로고에 index 페이지로 갈 수 있도록 링크 달기
