### ISSUE TITLE
#08 개인 일정 조회 페이지

### ISSUE THREAD

**Issue by jinho9613** [jinho9613/work_logstack#8]
로그인 했을때 개인 일정 조회 페이지 ( 오늘 예상 출/퇴근 시간, 근무 시작하기 버튼, (추가 기능) to do list)
 - 팀장의 경우 스케줄 조회 페이지로 이동

**Comment by yoon-myunghoon** [comment]
명훈 진행중

**Comment by yoon-myunghoon** [comment]
authy.views에 login 로직을 따로 만들어서 매니저인 경우와 아닌 경우에 대해 각각 redirect를 해줌
- 매니저인 경우엔 스케줄 조회 페이지로 이동
- 매니저가 아닌 경우엔 개인 일정 조회 페이지로 이동
개인 일정 조회 페이지에서는 예정된 출퇴근 시간과 업무 시작 버튼을 추가했음
- 만약 예정된 출퇴근 시간이 없으면, 예정된 출퇴근 시간 정보오 업무 시작 버튼을 보여주지 않음

**Comment by yoon-myunghoon** [comment]
to do list는 일단 보류
